// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://amhqnrsobiwpwmfplhry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtaHFucnNvYml3cHdtZnBsaHJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ3NDg0NzMsImV4cCI6MjA1MDMyNDQ3M30.8N3axyAJayWI9I8vuE0su7tnT4a7oMc-wTcDwxjEXSY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);